/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Arbol(props) {
  const { nodes, materials } = useGLTF("../models/Arbol.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.1} position={[0,0,0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0.geometry}
          material={nodes.mesh_0.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_2.geometry}
          material={nodes.mesh_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_1.geometry}
          material={nodes.mesh_1.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("../models/Arbol.glb");
