/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useControls } from "leva";

export function Merlin(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("../models/Merlin.glb");
  const { actions, names } = useAnimations(animations, group);
  
  const { animationName } = useControls({
    animationName: { options: names }
  })
  
  useEffect(() => {
    const action = actions[animationName]
    action 
              .reset()
              .fadeIn(0.5)
              .play()
              return () => {
                action.fadeOut(0.5)
            }
    
  }, [animationName])
  
  return (
    <group  ref={group} {...props} dispose={null}>
      <group scale={0.5} position={[-5,0,2]}>
        <group name="Geometry">
          <group name="Merlin_Props">
            <skinnedMesh
              name="Merlin_magic_stick"
              geometry={nodes.Merlin_magic_stick.geometry}
              material={nodes.Merlin_magic_stick.material}
              skeleton={nodes.Merlin_magic_stick.skeleton}
            />
            <skinnedMesh
              name="Merlin_trumpet"
              geometry={nodes.Merlin_trumpet.geometry}
              material={nodes.Merlin_trumpet.material}
              skeleton={nodes.Merlin_trumpet.skeleton}
            />
            <skinnedMesh
              name="Merlin_bulb"
              geometry={nodes.Merlin_bulb.geometry}
              material={nodes.Merlin_bulb.material}
              skeleton={nodes.Merlin_bulb.skeleton}
            />
            <skinnedMesh
              name="Merlin_trophy"
              geometry={nodes.Merlin_trophy.geometry}
              material={nodes.Merlin_trophy.material}
              skeleton={nodes.Merlin_trophy.skeleton}
            />
            <skinnedMesh
              name="Merlin_clouds"
              geometry={nodes.Merlin_clouds.geometry}
              material={nodes.Merlin_clouds.material}
              skeleton={nodes.Merlin_clouds.skeleton}
            />
            <skinnedMesh
              name="Merlin_sparkles"
              geometry={nodes.Merlin_sparkles.geometry}
              material={nodes.Merlin_sparkles.material}
              skeleton={nodes.Merlin_sparkles.skeleton}
            />
          </group>
          <skinnedMesh
            name="Merlin"
            geometry={nodes.Merlin.geometry}
            material={nodes.Merlin.material}
            skeleton={nodes.Merlin.skeleton}
          />
        </group>
        <primitive object={nodes.Root} />
      </group>
    </group>
  );
}

useGLTF.preload("../models/Merlin.glb");
